# arxivの学問領域の指定
subject: cat:hep-ph OR cat:hep-th OR cat:hep-ex OR cat:astro-ph.CO OR cond-mat.str-el OR cond-mat.mes-hall OR cond-mat.other

# 検索キーワード
keywords:
        light dark matter: 5
        vacuum stability: 3
        vacuum decay: 3
        topological: 3
        phonon: 2
        magnon: 2
        polariton: 2
        birefringence: 2
        grand unification: 2
        unified theory: 2
        NANOGrav: 2
        direct detection: 1

# 通知の閾値
score_threshold: 0
